### ISSUE TITLE
Displaying elapsed time in Discord output

### ISSUE THREAD

**Issue by Flosus** [stokbaek/simc-discord#15]
It would be useful to get the elapsed time when using the bot.

An additional nie to have would be a progressbar. I will see if I have the time to get a PR up.

**Comment by stokbaek** [comment]
I think this will be one of the harder things to do. This is why I haven't looked into having the bot doing this. This is something that I want to add when all other minor issues has been worked out.

If you manage to make this yourself a PR is more than welcome.

**Comment by Flosus** [comment]
I was thinking about using the output of simcraft, which already provides a progress bar.

As for the elapsed time, I simply would use the start and end time from the [loop](https://github.com/stokbaek/simc-discord/blob/master/simc.py#L56). Any other ideas?
