### ISSUE TITLE
Infinnite Loop

### ISSUE THREAD

**Issue by Phied** [stokbaek/simc-discord#29]
On your more recent revisions, the bot would never stop the simulation.  It looks like you had the processes going into an infinnite loop.  I did a quick and dirty fix, I'm sure it's not very ideal but it was able to get it working.  I am running this on FreeBSD.  What I did to fix it is below:

        if len(process_check) > 1:
            print("greater than 1.")
            if 'report took' in process_check[-2]:
                loop = False
                link = 'Simulation: %ssims/%s/%s.html' % (website, char, filename)
                await bot.change_presence(status=discord.Status.online, game=discord.Game(name='Sim: Ready'))
                await bot.edit_message(load, link + ' {0.author.mention}'.format(message))
                process.terminate()
            elif 'Generating' in process_check[-1]:
                done = '▒^▒^▒' * (20 - process_check[-1].count('.'))
                missing = '▒^▒^▒' * (process_check[-1].count('.'))
                progressbar = done + missing
                procent = 100 - process_check[-1].count('.') * 5
                load = await bot.edit_message(load, process_check[-1].split()[1] + ' ' + progressbar + ' ' +
                                             str(procent) + '%')
            else:
                print("Finished Generating!")
                loop = False
                link = 'Simulation: %ssims/%s/%s.html' % (website, char, filename)
                await bot.change_presence(status=discord.Status.online, game=discord.Game(name='Sim: Ready'))
                await bot.edit_message(load, link + ' {0.author.mention}'.format(message))
                process.terminate()
                print("DONE!")

**Comment by stokbaek** [comment]
When this loop happens did that simulationcraft not output any errors?

Errors in simulationcraft should be registred in the if statement above, or is something else happening where simulationcraft doesn't output any form of error?

**Comment by Phied** [comment]
Actually, there were no errors reported.  The process_check was only outputting blank lines.  Because this was constantly blank, it never matched 'report took' or 'Generating'.  I'm not sure why it would do only blank lines.  It's like it would start and work great, then all of a sudden it finished, but it wouldn't catch the 'report took' at the end of the line and continue looping forever and never finish.  This kept the bot always simulating even when the html report was actually created.

**Comment by stokbaek** [comment]
hmm sounds wierd. I know this was happening if it was a healing spec, but healing should be blocked now by looking up either armory or looking in the output of simc addon

**Comment by Phied** [comment]
Yea, healing would tell you that it isn't supported at all.  It could just be something that's different on my compiling of simc.  FreeBSD was a royal pain to get to work.  I actually need to open a ticket with them to include some extra header files to get it to work out of the box.  They also need to tell you in their directions to use gmake instead of make on FreeBSD.

**Comment by stokbaek** [comment]
yes, I tried to compile it in FreeBSD when I made the bot, but gave up. Was too much of a hassle. Sadly I think this is a FreeBSD issue, the hack you made can make it go wrong really fast sadly. I wont include this but I will keep my eye and see if it starts happening on other OS's too.
