### ISSUE TITLE
Default Iteration count and parameters

### ISSUE THREAD

**Issue by Flosus** [stokbaek/simc-discord#7]
It might be practical to extend the configuration with an default iteration count.

An option to allow the sending of iterations as a parameter when calling a bot would also be an option but I think it would be wise to disable this parameter in the default case.

The new parameter could look like `-i 25000`.

The config could get expanded like this:

```
      region": "eu"
    }
  ],
  "simcraft_opt": [
    {
      "allow_iteration_parameter": false,
      "default_iterations": 25000
    }
  ]
}
```

Any other opinions?

**Comment by stokbaek** [comment]
I did think about making iterations something that could be custom set, but as far as I know is there no reason to go above 25000 when doing stat weights as the gain is very minimal above 25000.

This is not hard to implement though.

**Comment by Flosus** [comment]
It's right that the benefits over 25000 are minimal, but for a quick DPS check you might want to lower the amount of iterations you do.

**Comment by stokbaek** [comment]
That is true. I am running it with 8 threads right now and takes around 12 secs to do a sim without scaling. This is way I haven't bothered with it.

I will take a look at it. This could be good if you dont have that much CPU power if you just want to do quick DPS checks.

**Comment by Flosus** [comment]
I had my personal server in mind, which isn't very well equiped. I haven't tested it yet, but I think it might take a while. I will try it later and let you know if any problems occure. (which is an Ubuntu 16.04)

**Comment by stokbaek** [comment]
This has now been added in PR https://github.com/stokbaek/simc-discord/pull/8
